### PR TITLE
[FEATURES] Support image encoder with image caption as example

### PR DESCRIPTION
**Pull request by lianqing11**
Support image encoder with image caption as example.

Try model: BLIP with Salesforce/blip-image-captioning-bas

Discussion:
+ the name of arch_type: visionEncoder_decoder
+ format the data with image_text
+ Should we generate another class inherited from HFEncoderDecoder?

### CODE REVIEW

**Review by research4pan — CHANGES_REQUESTED** [review]
Thanks! 👍  A first step towards multimodal in LMFlow! Some issues that may be better resolved before merging into main.

### `scripts/inference_multimodal_model.sh`

- [Interface] line 12: use `CUDA_VISIBLE_DEVICES=0` so that most users can run.
- [Style] line 16: better use `vision_encoder_decoder` instead of `visionEncoder_decoder` according to [google python coding style](https://google.github.io/styleguide/pyguide.html#316-naming).

### `examples/inferencer.py`

- ⚠️ [Feature] line 68: As only the image field for `input_dataset` is used, `input_dataset` should have format `image_only`. `image2text` dataset type can be used for finetuning the model `vision_encoder_decodre`.
- ⚠️ [Feature] line 75: As only the text field for `output` is used, `output` should have format `text_only`.
- [Style] line 70: "images" -> "image".

### `src/lmflow/args.py`

- [Style] line 124: better use `vision_encoder_decoder` instead of `visionEncoder_decoder` according to [google python coding style](https://google.github.io/styleguide/pyguide.html#316-naming).

### `src/lmflow/datasets/dataset.py`

- [Style] line 33: `image_text` -> `image2text`.

### `src/lmflow/models/hf_encoder_decoder_model.py`

- [Style] line 53: can be move to line 20. General package import order: standard packages, third party packages and self-defined packages, where sorted alphabetically in each category.
-⚠️ [Question] line 286, 294: will this cause problem for inference of encoder-decoder models?

### `src/lmflow/pipeline/inferencer.py`

- [Style] line 29: `image_text` -> `image2text`.
- [Style] line 93: better remove extra backslash "\".

### `src/lmflow/utils/constants.py`

- [Style] line 170: `image_text` -> `image2text`.

**Comment by lianqing11** [comment]
I have fixed the code style issues. 

Regarding to "[Question] line 286, 294: will this cause problem for inference of encoder-decoder models?", the pad_token_id argument is added to the kwargs, so it will not cause the problem for inference of encoder-decoder models.

I will add more features in this pr.

**Review by research4pan — APPROVED** [review]
Image encoder is an extremely important component for lmflow's multimodal functionality. Thanks!

### `src/lmflow/utils/constants`

- [Style] line 170: as this field only contains one image normally, using "image" instead of "images" would be better.

**Review by research4pan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
