### PR TITLE
[ADD] T2I finetuning with SD1 and SD2 to contrib

### PR DESCRIPTION
**Pull request by Aziily**
Text to image fine-tuning support for Stable Diffusion 1 and 2 series.

### CODE REVIEW

**Comment by Aziily** [comment]
I add a link for a small subset for dreambooth's dog as the example,
[dog_t2i_data_example](https://drive.google.com/drive/folders/106ahvIrXbiuZMBw0NuOTjY0vnM_xXARW?usp=sharing)

**Review by research4pan — COMMENTED** [review]
Some improvements that can be made before merging into main.

### `contrib/text2image/finetune_t2i.sh`

- [Style] line 7: I am wondering if an example file can be provided here.
- [Style] line 3, 7: Better export `--model_name_or_path`, `--dataset_path` for customization.

### `README`

- A `README` is preferred for the usage of the shell scripts, which 1) illustrates the dataset format, 2) and specifies environments (such as operating system, GPU version), 3) also how to customize the script.

### `contrib/text2image/requirements.txt`

- Better specify the lowest required version of `diffuser`, e.g. `diffuser >= x.xx.xx`.

**Comment by Aziily** [comment]
Thanks for your advice. Here, I add script arguments according to `scripts/run_finetune.sh` and version requirements. Also, a readme is added for env/data preparation and script usage.

**Review by research4pan — APPROVED** [review]
LGTM

**Pull request merged**
